[package]
name = "william_shakespeare"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.6.1"
rand = "0.8.5"
rand_distr = "0.4.3"
tokio = { version = "1.39.2", features = ["rt-multi-thread"]}
